### PR TITLE
First efforts on creating a PropertyGrid

### PR DESCRIPTION
**Pull request by thiagojedi**
So... I was reading again the PR comments on the Monogame repo, and Tom said:

> It is a little more complex... but sort of. The value side of the property grid can be more than just text, could be text + button, a combobox, a check box, etc. Also you have expanding sections which can be rolled up to hide some nested grid items.
> If we get something working well it might be worth contributing it back to XWT. If they had a complete set of controls we could just use it across all platforms.
> https://github.com/mono/MonoGame/pull/2441#issuecomment-47991196

So I tried to create a PropertyGrid using only Xwt controls and created a Mockup.

I think it's doing good. Have a look, please.

### CODE REVIEW

**Comment by thiagojedi** [comment]
Oh... Reviewing again, that was your idea at first... 
Anyway, that was a prototype...

The issues I found 'till now:
- It's kinda heavyweight... I mean, when I put a lot of categories the scroll feels slow...
- I can't see how to implement nested properties
- For some reason, it looks ugly :worried:

The best looking approach I see in XWT alone is extending the TreeView. The TreeView, as it is now, only supports Images, Text and Checkboxes... But I'm looking on how to add suppot at least for ComboBoxes... 

I'll try the native WPF you linked on that issue (mono#2441) now.

**Comment by KonajuGames** [comment]
Cool.  I've got some local changes that generate the project files using
Protobuild and trying to get it running on Mac.​  I'll have a look at this
property grid.

**Comment by thiagojedi** [comment]
Great! 

Try to run with Xwt.Mac too, as we don't have specific code yet, to see if there any issue.

**Comment by KonajuGames** [comment]
Already built Xwt.Mac and selecting it with ToolkitType.Cocoa.​  The
application isn't running yet, but close.

**Comment by thiagojedi** [comment]
I changed the TextEntry for a Canvas and I draw the text there.
It corrected the multiline issue here on Linux+Gtk.
Please see if it works on WPF and Mac.

And tell me if you need any changes on the PropertyGrid visual...

**Comment by KonajuGames** [comment]
> I changed the TextEntry for a Canvas and I draw the text there.

That won't work as a solution because you won't be able to highlight
sections and copy the text.  Need to find a way to use the native
multi-line text controls.  If that means going to native GTK# on Linux and
Cocoa on Mac rather than the XWT wrapper, that may be the way we have to go.

**Comment by thiagojedi** [comment]
> If that means going to native GTK# on Linux and
> Cocoa on Mac rather than the XWT wrapper, that may be the way we have to go. 

I'm starting to accept this idea too... The other way would be contribute back to Xwt but I think it would be faster if we go with the native libs.

I can start the port to GTK# but I'll keep the PropertyGrid structure (with expanders, label and stuff...).

**Comment by thiagojedi** [comment]
They just created a PR with the TextEntry.Multiline implementatition to Xwt.Gtk, I'll keep a eye on it. 

Please investigate if the TextEntry.Multiline property works on Xwt.Mac... I don't think so, but doesn't hurt to try...

**Comment by KonajuGames** [comment]
The Xwt multiline text entry does work on Mac.  I've used it to convert a
.contentproj to .mgcb and build some content.  Until it got to a spritefont
that failed, which I am working to fix in MGCB now.​

**Pull request closed without merging**
